# -*- coding: utf-8 -*-
"""
Created on Mon Oct 21 00:21:43 2019

@author: meadh
"""

import random

all_menu = {
       "edamame" : 104,
       "wok fried greens" : 111,
       "raw salad" : 105,
       "tori kara age" : 107,
       "chicken wings" : 112,
       "ebi katsu" : 103,
       "chilli squid" : 110,
       "bang bang cauliflower" : 114,
       "duck pancakes" : 118,
       "lettuce wraps" : 119,
       "beef bao" : 113,
       "pork bao" : 115,
       "yasai bao" : 116,
       "yasai gyoza" : 101,
       "chicken gyoza" : 100,
       "pork gyoza" : 106,
       "prawn gyoza" : 102,
       "duck gyoza" : 99,
       "rice" : 300,
       "noodles" : 301,
       "kimchi" : 302,
       "tea-stained egg" : 307,
       "chillies" : 303,
       "pickles" : 304,
       "miso soup" : 109,
        "grilled duck donburi" : 54,
       "chicken teriyaki donburi" : 58,
       "beef teriyaki donburi" : 57,
       "chicken and prawn cha han" : 77,
       "yasai cha han" : 78,
       "chilli chicken salad" : 52,
       "chilli yasai salad" : 55,
       "pad thai salad" : 56,
       "grilled duck ramen" : 30,
       "shirodashi ramen" : 31,
       "chicken ramen" : 20,
       "wagamama ramen" : 21,
       "chilli chicken ramen" : 25,
       "chilli steak ramen" : 24,
       "kare burosu ramen" : 23,
       "chu chee" : 65,
       "grilled tuna" : 53,
       "steak teriyaki soba" : 66,
       "salmon teriyaki soba" : 67,
       "chicken teriyaki soba" : 68,
       "chicken and prawn yaki soba" : 40,
       "yasai yaki soba" : 41,
       "yaki udon" : 42,
       "chicken and prawn pad thai" : 46,
       "yasai pad thai" : 47,
       "ginger chicken udon" : 48,
       "chicken samla" : 50,
       "yasai samla" : 49,
       "chicken firecracker" : 62,
       "prawn firecracker" : 63,
       "yasai itame" : 38,
       "chicken itame" : 37,
       "prawn itame" : 34,
       "chicken raisukaree" : 60,
       "prawn raisukaree" : 79,
       "yasai katsu" : 72,
       "chicken katsu" : 71,
       "coke zero" : 804,
       "coke" : 803,
       "7up" : 806,
       "7up free" : 807,
       "club orange" : 805,
       "can coke zero" : 904,
       "can coke" : 903,
       "can 7up" : 906,
       "can 7up free" : 907,
       "can club orange" : 905,
       "lemonade" : 812,
       "peach iced tea" : 808,
       "milk" : 809,
       "small still water" : 801,
       "large still water" : 810,
       "small sparkling water" : 802,
       "large sparkling water" : 811,
       "green tea" : 90,
       "small rose" : 611,
       "large rose" : 612,
       "bottle rose" : 613,
       "small house white" : 411,
       "large house white" : 412,
       "bottle house white" : 413,
       "small premium white" : 421,
       "large premium white" : 422,
       "bottle premium white" : 423,
       "small house red" : 511,
       "large house red" : 512,
       "bottle house red" : 513,
       "small premium red" : 521,
       "large premium red" : 522,
       "bottle premium red" : 523,
       "sachetto prosecco" : 631,
       "treviso prosecco" : 633,
       "sho chiku bai" : 601,
       "plum wine" : 602,
       "bottle heineken" : 716,
       "bottle heineken 00" : 714,
       "bottle singha" : 705,
       "glass tiger" : 700,
       "pint tiger" : 701,
       "glass asahi" : 702,
       "pint asahi" : 709,
       "orchard thieves" : 708,
       "kirin" : 715,
       "fruit juice" : 2,
       "orange juice" : 3,
       "tropical juice" : 6,
       "clean green juice" : 7,
       "blueberry spice juice" : 8,
       "super green juice" : 9,
       "positive juice" : 17,
       "power juice" : 18,
       "repair juice" : 19,
       "cheesecake" : 271,
       "chocolate cake" : 272,
       "carrot cake" : 273,
       "mini cakes" : 275,
       "banana katsu" : 279,
       "coconut reika ice cream" : 270,
       "salted caramel ice cream" : 276,
       "vanilla pod ice cream" : 277,
       "yuzu ice cream" : 278,
       "selection of ice creams" : 281,
       "raspberry sorbet" : 280,
       "herbal tea" : 91,
       "jasmine tea" : 900,
       "mint tea" : 901,
       "americano" : 91,
       "espresso" : 93,
       "double espresso" : 94,
       "cappucino" : 95,
       "latte" : 96,
       "mini chicken ramen" : 80,
       "mini yasai ramen" : 81,
       "mini chicken yaki soba" : 88,
       "mini yasai yaki soba" : 89,
       "mini grilled noodles with chicken" : 75,
       "mini grilled noodles with fish" : 75,
       "mini fresh juice" : 16,
       "kid's milk" : 8,
       "mini chicken cha han" : 86,
       "mini yasai cha han" : 87,
       "mini chicken katsu" : 82,
       "mini grilled chicken" : 82,
       "mini yasai katsu" : 83,
       "kid's ice cream" : 11 
       }

def ask_all():
    item = random.choice(list(all_menu.keys()))
    return item

def answer_all(number, item):
    if number == all_menu[item]:
        return True
    else:
        return False
    
def get_all_number(item):
    return str(all_menu[item])
        
